addons:
  apt:
    packages:
      - lynx
      
language: android

jdk:
  - oraclejdk8
  
android:
    components:
    - tools
    - platform-tools
    - android-25
    - build-tools-25.0.3

notifications:
  email: false

before_install:  
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  
after_failure:
  - if [ -f /home/travis/build/IvanLepi/PopularMovies/app/build/reports/lint-results.html ]; then lynx -dump /home/travis/build/IvanLepi/PopularMovies/app/build/reports/lint-results.html;


 
