language: android
android:
    components:
    # Update Android SDK Tools
    - tools

    - build-tools-25.0.3
    - android-25

    # Support library
    - extra-android-support
    - extra-android-m2repository

notifications:
  email: false

before_install:  
  - chmod +x gradlew

 
